# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\stefa\Uni\AdvPT\Project\Git-project\advpt-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\stefa\Uni\AdvPT\Project\Git-project\advpt-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2020.2.4\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\stefa\Uni\AdvPT\Project\Git-project\advpt-project\CMakeFiles C:\Users\stefa\Uni\AdvPT\Project\Git-project\advpt-project\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\stefa\Uni\AdvPT\Project\Git-project\advpt-project\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named advpt_project

# Build rule for target.
advpt_project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 advpt_project
.PHONY : advpt_project

# fast build rule for target.
advpt_project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/build
.PHONY : advpt_project/fast

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/source/BuildFactoryEvent.obj: src/source/BuildFactoryEvent.cpp.obj

.PHONY : src/source/BuildFactoryEvent.obj

# target to build an object file
src/source/BuildFactoryEvent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/BuildFactoryEvent.cpp.obj
.PHONY : src/source/BuildFactoryEvent.cpp.obj

src/source/BuildFactoryEvent.i: src/source/BuildFactoryEvent.cpp.i

.PHONY : src/source/BuildFactoryEvent.i

# target to preprocess a source file
src/source/BuildFactoryEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/BuildFactoryEvent.cpp.i
.PHONY : src/source/BuildFactoryEvent.cpp.i

src/source/BuildFactoryEvent.s: src/source/BuildFactoryEvent.cpp.s

.PHONY : src/source/BuildFactoryEvent.s

# target to generate assembly for a file
src/source/BuildFactoryEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/BuildFactoryEvent.cpp.s
.PHONY : src/source/BuildFactoryEvent.cpp.s

src/source/DestroyFactoryEvent.obj: src/source/DestroyFactoryEvent.cpp.obj

.PHONY : src/source/DestroyFactoryEvent.obj

# target to build an object file
src/source/DestroyFactoryEvent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/DestroyFactoryEvent.cpp.obj
.PHONY : src/source/DestroyFactoryEvent.cpp.obj

src/source/DestroyFactoryEvent.i: src/source/DestroyFactoryEvent.cpp.i

.PHONY : src/source/DestroyFactoryEvent.i

# target to preprocess a source file
src/source/DestroyFactoryEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/DestroyFactoryEvent.cpp.i
.PHONY : src/source/DestroyFactoryEvent.cpp.i

src/source/DestroyFactoryEvent.s: src/source/DestroyFactoryEvent.cpp.s

.PHONY : src/source/DestroyFactoryEvent.s

# target to generate assembly for a file
src/source/DestroyFactoryEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/DestroyFactoryEvent.cpp.s
.PHONY : src/source/DestroyFactoryEvent.cpp.s

src/source/Event.obj: src/source/Event.cpp.obj

.PHONY : src/source/Event.obj

# target to build an object file
src/source/Event.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Event.cpp.obj
.PHONY : src/source/Event.cpp.obj

src/source/Event.i: src/source/Event.cpp.i

.PHONY : src/source/Event.i

# target to preprocess a source file
src/source/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Event.cpp.i
.PHONY : src/source/Event.cpp.i

src/source/Event.s: src/source/Event.cpp.s

.PHONY : src/source/Event.s

# target to generate assembly for a file
src/source/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Event.cpp.s
.PHONY : src/source/Event.cpp.s

src/source/Factory.obj: src/source/Factory.cpp.obj

.PHONY : src/source/Factory.obj

# target to build an object file
src/source/Factory.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Factory.cpp.obj
.PHONY : src/source/Factory.cpp.obj

src/source/Factory.i: src/source/Factory.cpp.i

.PHONY : src/source/Factory.i

# target to preprocess a source file
src/source/Factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Factory.cpp.i
.PHONY : src/source/Factory.cpp.i

src/source/Factory.s: src/source/Factory.cpp.s

.PHONY : src/source/Factory.s

# target to generate assembly for a file
src/source/Factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Factory.cpp.s
.PHONY : src/source/Factory.cpp.s

src/source/GameEntity.obj: src/source/GameEntity.cpp.obj

.PHONY : src/source/GameEntity.obj

# target to build an object file
src/source/GameEntity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/GameEntity.cpp.obj
.PHONY : src/source/GameEntity.cpp.obj

src/source/GameEntity.i: src/source/GameEntity.cpp.i

.PHONY : src/source/GameEntity.i

# target to preprocess a source file
src/source/GameEntity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/GameEntity.cpp.i
.PHONY : src/source/GameEntity.cpp.i

src/source/GameEntity.s: src/source/GameEntity.cpp.s

.PHONY : src/source/GameEntity.s

# target to generate assembly for a file
src/source/GameEntity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/GameEntity.cpp.s
.PHONY : src/source/GameEntity.cpp.s

src/source/Recipe.obj: src/source/Recipe.cpp.obj

.PHONY : src/source/Recipe.obj

# target to build an object file
src/source/Recipe.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Recipe.cpp.obj
.PHONY : src/source/Recipe.cpp.obj

src/source/Recipe.i: src/source/Recipe.cpp.i

.PHONY : src/source/Recipe.i

# target to preprocess a source file
src/source/Recipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Recipe.cpp.i
.PHONY : src/source/Recipe.cpp.i

src/source/Recipe.s: src/source/Recipe.cpp.s

.PHONY : src/source/Recipe.s

# target to generate assembly for a file
src/source/Recipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Recipe.cpp.s
.PHONY : src/source/Recipe.cpp.s

src/source/ResearchEvent.obj: src/source/ResearchEvent.cpp.obj

.PHONY : src/source/ResearchEvent.obj

# target to build an object file
src/source/ResearchEvent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/ResearchEvent.cpp.obj
.PHONY : src/source/ResearchEvent.cpp.obj

src/source/ResearchEvent.i: src/source/ResearchEvent.cpp.i

.PHONY : src/source/ResearchEvent.i

# target to preprocess a source file
src/source/ResearchEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/ResearchEvent.cpp.i
.PHONY : src/source/ResearchEvent.cpp.i

src/source/ResearchEvent.s: src/source/ResearchEvent.cpp.s

.PHONY : src/source/ResearchEvent.s

# target to generate assembly for a file
src/source/ResearchEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/ResearchEvent.cpp.s
.PHONY : src/source/ResearchEvent.cpp.s

src/source/SolLoader.obj: src/source/SolLoader.cpp.obj

.PHONY : src/source/SolLoader.obj

# target to build an object file
src/source/SolLoader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/SolLoader.cpp.obj
.PHONY : src/source/SolLoader.cpp.obj

src/source/SolLoader.i: src/source/SolLoader.cpp.i

.PHONY : src/source/SolLoader.i

# target to preprocess a source file
src/source/SolLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/SolLoader.cpp.i
.PHONY : src/source/SolLoader.cpp.i

src/source/SolLoader.s: src/source/SolLoader.cpp.s

.PHONY : src/source/SolLoader.s

# target to generate assembly for a file
src/source/SolLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/SolLoader.cpp.s
.PHONY : src/source/SolLoader.cpp.s

src/source/Solution.obj: src/source/Solution.cpp.obj

.PHONY : src/source/Solution.obj

# target to build an object file
src/source/Solution.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Solution.cpp.obj
.PHONY : src/source/Solution.cpp.obj

src/source/Solution.i: src/source/Solution.cpp.i

.PHONY : src/source/Solution.i

# target to preprocess a source file
src/source/Solution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Solution.cpp.i
.PHONY : src/source/Solution.cpp.i

src/source/Solution.s: src/source/Solution.cpp.s

.PHONY : src/source/Solution.s

# target to generate assembly for a file
src/source/Solution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Solution.cpp.s
.PHONY : src/source/Solution.cpp.s

src/source/StartFactoryEvent.obj: src/source/StartFactoryEvent.cpp.obj

.PHONY : src/source/StartFactoryEvent.obj

# target to build an object file
src/source/StartFactoryEvent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/StartFactoryEvent.cpp.obj
.PHONY : src/source/StartFactoryEvent.cpp.obj

src/source/StartFactoryEvent.i: src/source/StartFactoryEvent.cpp.i

.PHONY : src/source/StartFactoryEvent.i

# target to preprocess a source file
src/source/StartFactoryEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/StartFactoryEvent.cpp.i
.PHONY : src/source/StartFactoryEvent.cpp.i

src/source/StartFactoryEvent.s: src/source/StartFactoryEvent.cpp.s

.PHONY : src/source/StartFactoryEvent.s

# target to generate assembly for a file
src/source/StartFactoryEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/StartFactoryEvent.cpp.s
.PHONY : src/source/StartFactoryEvent.cpp.s

src/source/StopFactoryEvent.obj: src/source/StopFactoryEvent.cpp.obj

.PHONY : src/source/StopFactoryEvent.obj

# target to build an object file
src/source/StopFactoryEvent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/StopFactoryEvent.cpp.obj
.PHONY : src/source/StopFactoryEvent.cpp.obj

src/source/StopFactoryEvent.i: src/source/StopFactoryEvent.cpp.i

.PHONY : src/source/StopFactoryEvent.i

# target to preprocess a source file
src/source/StopFactoryEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/StopFactoryEvent.cpp.i
.PHONY : src/source/StopFactoryEvent.cpp.i

src/source/StopFactoryEvent.s: src/source/StopFactoryEvent.cpp.s

.PHONY : src/source/StopFactoryEvent.s

# target to generate assembly for a file
src/source/StopFactoryEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/StopFactoryEvent.cpp.s
.PHONY : src/source/StopFactoryEvent.cpp.s

src/source/Technology.obj: src/source/Technology.cpp.obj

.PHONY : src/source/Technology.obj

# target to build an object file
src/source/Technology.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Technology.cpp.obj
.PHONY : src/source/Technology.cpp.obj

src/source/Technology.i: src/source/Technology.cpp.i

.PHONY : src/source/Technology.i

# target to preprocess a source file
src/source/Technology.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Technology.cpp.i
.PHONY : src/source/Technology.cpp.i

src/source/Technology.s: src/source/Technology.cpp.s

.PHONY : src/source/Technology.s

# target to generate assembly for a file
src/source/Technology.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Technology.cpp.s
.PHONY : src/source/Technology.cpp.s

src/source/Utils.obj: src/source/Utils.cpp.obj

.PHONY : src/source/Utils.obj

# target to build an object file
src/source/Utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Utils.cpp.obj
.PHONY : src/source/Utils.cpp.obj

src/source/Utils.i: src/source/Utils.cpp.i

.PHONY : src/source/Utils.i

# target to preprocess a source file
src/source/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Utils.cpp.i
.PHONY : src/source/Utils.cpp.i

src/source/Utils.s: src/source/Utils.cpp.s

.PHONY : src/source/Utils.s

# target to generate assembly for a file
src/source/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/Utils.cpp.s
.PHONY : src/source/Utils.cpp.s

src/source/VictoryEvent.obj: src/source/VictoryEvent.cpp.obj

.PHONY : src/source/VictoryEvent.obj

# target to build an object file
src/source/VictoryEvent.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/VictoryEvent.cpp.obj
.PHONY : src/source/VictoryEvent.cpp.obj

src/source/VictoryEvent.i: src/source/VictoryEvent.cpp.i

.PHONY : src/source/VictoryEvent.i

# target to preprocess a source file
src/source/VictoryEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/VictoryEvent.cpp.i
.PHONY : src/source/VictoryEvent.cpp.i

src/source/VictoryEvent.s: src/source/VictoryEvent.cpp.s

.PHONY : src/source/VictoryEvent.s

# target to generate assembly for a file
src/source/VictoryEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\advpt_project.dir\build.make CMakeFiles/advpt_project.dir/src/source/VictoryEvent.cpp.s
.PHONY : src/source/VictoryEvent.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... advpt_project
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/source/BuildFactoryEvent.obj
	@echo ... src/source/BuildFactoryEvent.i
	@echo ... src/source/BuildFactoryEvent.s
	@echo ... src/source/DestroyFactoryEvent.obj
	@echo ... src/source/DestroyFactoryEvent.i
	@echo ... src/source/DestroyFactoryEvent.s
	@echo ... src/source/Event.obj
	@echo ... src/source/Event.i
	@echo ... src/source/Event.s
	@echo ... src/source/Factory.obj
	@echo ... src/source/Factory.i
	@echo ... src/source/Factory.s
	@echo ... src/source/GameEntity.obj
	@echo ... src/source/GameEntity.i
	@echo ... src/source/GameEntity.s
	@echo ... src/source/Recipe.obj
	@echo ... src/source/Recipe.i
	@echo ... src/source/Recipe.s
	@echo ... src/source/ResearchEvent.obj
	@echo ... src/source/ResearchEvent.i
	@echo ... src/source/ResearchEvent.s
	@echo ... src/source/SolLoader.obj
	@echo ... src/source/SolLoader.i
	@echo ... src/source/SolLoader.s
	@echo ... src/source/Solution.obj
	@echo ... src/source/Solution.i
	@echo ... src/source/Solution.s
	@echo ... src/source/StartFactoryEvent.obj
	@echo ... src/source/StartFactoryEvent.i
	@echo ... src/source/StartFactoryEvent.s
	@echo ... src/source/StopFactoryEvent.obj
	@echo ... src/source/StopFactoryEvent.i
	@echo ... src/source/StopFactoryEvent.s
	@echo ... src/source/Technology.obj
	@echo ... src/source/Technology.i
	@echo ... src/source/Technology.s
	@echo ... src/source/Utils.obj
	@echo ... src/source/Utils.i
	@echo ... src/source/Utils.s
	@echo ... src/source/VictoryEvent.obj
	@echo ... src/source/VictoryEvent.i
	@echo ... src/source/VictoryEvent.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

